import { WorkspaceBlock, GlobalVariable, EventHandler } from './types';
import { generateHandlerCode } from './eventHandlers';

export function assembleCode(
  blocks: WorkspaceBlock[],
  globalVariables: GlobalVariable[],
  eventHandlers: EventHandler[]
): string {
  const mainBlocks = blocks.filter(b => b.section === 'main').sort((a, b) => a.position - b.position);
  const enabledHandlers = eventHandlers.filter(h => h.enabled);
  
  const header = `//+------------------------------------------------------------------+
//|                                                 Expert Advisor    |
//|                        Generated by MQL5 EA Builder               |
//|                                      ${new Date().toLocaleDateString()} |
//+------------------------------------------------------------------+

#property copyright "Generated by MQL5 EA Builder"
#property link      "https://mql5-builder.com"
#property version   "1.00"
#property strict

`;

  const includes = `//--- Include Files
#include <Trade\\Trade.mqh>

`;

  const globals = globalVariables.length > 0 ? `//--- Global Variables
${globalVariables.map(v => {
  let valueStr = String(v.currentValue);
  if (v.type === 'string') valueStr = `"${valueStr}"`;
  if (v.type === 'bool') valueStr = valueStr === 'true' ? 'true' : 'false';
  return `${v.type} ${v.name} = ${valueStr};  // ${v.description}`;
}).join('\n')}

` : '';

  const handlersCode = enabledHandlers.map(handler => generateHandlerCode(handler)).join('\n\n');

  const functions = mainBlocks.map(block => {
    return `//+------------------------------------------------------------------+
//| ${block.snippet.name.padEnd(65)}|
//+------------------------------------------------------------------+
${block.snippet.code}

`;
  }).join('\n');

  return header + includes + globals + handlersCode + '\n\n' + functions;
}

export function downloadCode(code: string, filename: string = 'expert-advisor.txt') {
  const blob = new Blob([code], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function getCodeStatistics(code: string) {
  const lines = code.split('\n').length;
  const functions = (code.match(/\w+\s+\w+\s*\([^)]*\)\s*{/g) || []).length;
  const comments = (code.match(/\/\/.*/g) || []).length;
  
  return {
    lines,
    functions,
    comments,
    characters: code.length,
  };
}
